site_name: Site de Hugo
repo_url: https://github.com/e-Tesseract/e-Tesseract.github.io.git

nav:
  - Home: index.md
  - Tresor Tropic: tresor_tropic_wiki.md
  - Comparaisons tris: compte_rendu_tri.md
  - Les champs de kebab en Asie: index2.md


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Theme sombre
      primary: deep-purple
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Theme clair
      primary: deep-purple
      accent: cyan
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    