site_name: Site de Hugo
repo_url: https://github.com/e-Tesseract/e-Tesseract.github.io.git

nav:
  - Home: index.md
  - Les champs de kebab en Asie: test.md


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Theme sombre
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Theme clair
      primary: teal
      accent: lime
    
    