site_name: Site de Hugo
repo_url: https://github.com/e-Tesseract/e-Tesseract.github.io.git

nav:
  - Home: index.md
  - Méthodes de tris: compte_rendu_tri.md
  - Tresor Tropic: tresor_tropic_wiki.md
  - Les champs de kebab en Asie: index2.md


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Theme sombre
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Theme clair
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - toc:
      permalink: true



extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/e-Tesseract
    